services:

  cloudflared:
    image: erisamoe/cloudflared
    container_name: calibre-web-cloudflared
    restart: unless-stopped
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: --hostname mylibrary.example.com --name mylibrary --url http://nginx:80
    # ^-- https://github.com/Erisa/cloudflared-docker/issues/5
    depends_on:
      - nginx

  nginx:
    container_name: calibre-web-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:0.6.21
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      #- DOCKER_MODS=linuxserver/mods:universal-calibre|ghcr.io/themepark-dev/theme.park:calibre-web-develop
      #- TP_DOMAIN=theme-park.dev
      #- TP_THEME=space-gray
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${PWD}/data:/config
      - ${PWD}/Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
