services:

  cloudflared:
    image: erisamoe/cloudflared
    container_name: calibre-web-cloudflared
    volumes:
      - ./cloudflared:/etc/cloudflared
    
    #command: --hostname books.mendhak.com --url http://nginx:80  
    # ^-- doesn't seem to work? https://github.com/Erisa/cloudflared-docker/issues/5
    command: tunnel run --url http://nginx:80 books
    depends_on:
      - nginx

  nginx:
    container_name: calibre-web-nginx
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:arm32v7-latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${PWD}/data:/config
      - ${PWD}/Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
